

set /p Build=<../VERSION
@SET LOGINEP_VERSION=%0-%Build%
@SET LOGINEP_LDAP_TIMEOUT=60
@SET LOGINEP_LDAP_HOST=unixldap.somehost.com
@SET LOGINEP_LDAP_PORT=123
@SET LOGINEP_LDAP_CONSUMERCLIENTID_PREFIX=ldap_
@SET LOGINEP_USER_BASE_DN=ou=People,ou=everyone,dc=somehost,dc=com
@SET LOGINEP_USER_ATTRIBUTE=uid
@SET LOGINEP_KONG_ADMINAPI_URL=http://kong:8001
@SET LOGINEP_SYNCACL=group1,group2,group3
@SET LOGINEP_JWT_TOKEN_TIMEOUT=60

python ./src/app.py